sudo: true
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk
env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="cookbooks"  

install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/bundle install
  - /opt/chefdk/embedded/bin/bundle exec foodcritic -f any . --exclude spec
  - /opt/chefdk/embedded/bin/bundle exec rspec ./cookbooks/helloworld/spec/helloworld.rb
  - /opt/chefdk/embedded/bin/bundle exec sudo chef-client -z "helloworld"
  
